name: newenv
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20230802.0
  - appnope=0.1.4
  - arrow-cpp=14.0.2
  - asttokens=2.0.5
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - bokeh=3.4.1
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.4
  - click=8.1.7
  - comm=0.2.2
  - contourpy=1.2.0
  - cytoolz=0.12.2
  - dask-core=2024.5.0
  - dask-expr=1.1.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - distributed=2024.5.0
  - executing=0.8.3
  - freetype=2.12.1
  - gflags=2.2.2
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - gtest=1.14.0
  - heapdict=1.0.1
  - icu=73.1
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.5
  - ipython=8.25.0
  - jedi=0.18.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libcxx=17.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - msgpack-python=1.0.3
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.3.1
  - orc=1.7.4
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-lmdb=1.4.1
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2022.04.01
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.1.10
  - sortedcontainers=2.4.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tblib=1.7.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - wheel=0.43.0
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.19.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - bs4==0.0.2
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - dask==2024.7.0
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.2.6
      - langchain-community==0.2.6
      - langchain-core==0.2.11
      - langchain-text-splitters==0.2.2
      - langchainhub==0.1.20
      - langsmith==0.1.84
      - marshmallow==3.21.3
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - neo4j==5.22.0
      - numpy==2.0.0
      - openai==1.35.10
      - orjson==3.10.6
      - partd==1.4.2
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - python-dotenv==1.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.31
      - tenacity==8.5.0
      - tiktoken==0.7.0
      - toolz==0.12.1
      - tqdm==4.66.4
      - types-requests==2.32.0.20240712
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - yarl==1.9.4
